# excel_to_sql project configuration
# sql first configuation

#-------#
# Paths #
#-------#
# Path to raw data (relative to project root)
data_dir: ./data/raw

#---------------#
# Global config #
#---------------#

project_name: excel_to_sql
validation_mode: strict # strict | permissive

source:
    type: excel
    file: messy_orders.xlsx
    header_row: 0

target:
    db_type: mssql
    driver: "ODBC Driver 17 for SQL Server"
    server: "localhost"
    database: "order_management"
    authentication:
        type: "windows" # "sql" or "windows"
        username: "my_user"
        password: "my_password"
    schema: "dbo"
    if_exists: "append"
    batch_size: 1000
    fast_executemany: true

#----------------#
# Cleaning rules #
#----------------#

cleaning:
    trim_whitespace: true
    standardise_nulls: true
    remove_blank_rows: true
    day_first_format: true
    currency_symbol: R

#-----------------------#
# Sheet → table mapping #
#-----------------------#

mappings:
    customers:
        sheet_name: Customers
        target_table: customers

    products:
        sheet_name: Products
        target_table: products

    orders:
        sheet_name: Orders
        target_table: orders

    order_items:
        sheet_name: OrderItems
        target_table: order_items

#-----------------------------#
# Notes about SQL data types  #
# Not all data types included #
#-----------------------------#

# SQL data types
# Exact numerics: tinyint, smallint, int, bigint, bit, decimal/numeric, money, smallmoney
# Approximate numerics: float, real
# Date and time: date, time, datetime
# Character strings: char, varchar, text
# Unicode character strings: nchar, nvarchar, ntext
# Binary strings: binary, varbinary, image

#--------------#
# Column rules #
#--------------#

columns:
    customers:
        customer_id:
            source_column: id
            data_type: int
            primary_key: true
            required: true
            validation:
                min_value: 1

        customer_name:
            source_column: name
            data_type: varchar(50)
            case: title # options: lower, upper, title, asis
            required: true
            validation:
                format: person_name
                nullable: true
                on_error: warn # fail | drop | warn

        email:
            source_column: email
            data_type: varchar(255)
            case: lower # options: lower, upper, title, asis
            required: true
            validation:
                format: email
                nullable: true
                check_deliverability: false
                on_error: warn # fail | drop | warn

        mobile:
            source_column: mobile
            data_type: varchar(20)
            required: true
            validation:
                format: E.164
                allow_local: true
                dialling_prefix: "+27"

        city:
            source_column: city
            data_type: varchar(30)
            case: title # options: lower, upper, title, asis
            required: true

        join_date:
            source_column: join_date
            data_type: date
            validation:
                min_value: 1900-01-01
                max_value: today

    products:
        product_id:
            source_column: product_id
            data_type: int
            primary_key: true
            required: true
            validation:
                min_value: 1001

        product_name:
            source_column: product_name
            data_type: varchar(50)
            case: title # options: lower, upper, title, asis
            required: true
            validation:
                format: product_name
                nullable: true
                on_error: fail # fail | drop | warn

        product_price:
            source_column: product_price
            data_type: money
            required: true
            validation:
                min_value: 1
                max_value: 1000000
                nullable: true
                on_error: fail # fail | drop | warn

        stock_quantity:
            source_column: stock_quantity
            data_type: int
            required: true
            validation:
                min_value: 0
                max_value: 1000000

    orders:
        order_id:
            source_column: order_id
            data_type: int
            primary_key: true
            required: true
            validation:
                min_value: 100

        customer_id:
            source_column: customer_id
            data_type: int
            required: true
            validation:
                foreign_key: customers.customer_id
                nullable: false

        order_date:
            source_column: order_date
            data_type: date
            required: true
            validation:
                min_value: 1900-01-01
                max_value: today
                nullable: true
                on_error: warn # fail | drop | warn

        order_status:
            source_column: status
            data_type: varchar(10)
            required: true
            value_mapping:
                completed:
                    - c
                    - complete
                    - done
                    - closed
                pending:
                    - p
                    - pending
                cancelled:
                    - x
                    - cancelled
            validation: nullable = true

    order_items:
        order_item_id:
            source_column: order_item_id
            data_type: int
            primary_key: true
            required: true

        order_id:
            source_column: order_id
            data_type: int
            required: true
            validation:
                foreign_key: orders.
                nullable: false

        product_id:
            source_column: product_id
            data_type: int
            required: true
            validation:
                foreign_key: products.product_id
                nullable: false

        quantity:
            source_column: quantity
            data_type: int
            required: true
            validation:
                min_value: 1
                max_value: 1000000
                on_error: fail # fail | drop | warn

        unit_price:
            source_column: unit_price
            data_type: money
            required: true
            validation:
                min_value: 1
                max_value: 1000000.00
                on_error: fail # fail | drop | warn

        total_price:
            source_column: total_price
            data_type: money
            validation:
                derived_from:
                    formula: "quantity * unit_price"
                    depends_on:
                        - quantity
                        - unit_price
