# excel_to_sql project configuration

#-------#
# Paths #
#-------#
# Path to raw data (relative to project root)
data_dir: ../data/raw

#---------------#
# Global config #
#---------------#

project_name: excel_to_sql

source:
    type: excel
    file: fake_data.xlsx
    locale: en_ZA
    header_row: 1

target:
    db_type: mssql
    driver: "ODBC Driver 17 for SQL Server"
    server: "localhost"
    database: "order_management"
    authentication:
        type: "windows" # "sql" or "windows"
        username: "my_user"
        password: "my_password"
    schema: "dbo"
    if_exists: "append"
    batch_size: 1000
    fast_executemany: true

#----------------#
# Cleaning rules #
#----------------#

cleaning:
    global:
        trim_whitespace: true
        standardise_nulls: true
        remove_blank_rows: true

#-----------------------#
# Sheet → table mapping #
#-----------------------#

mappings:
    customers:
        sheet_name: Customers
        target_table: customers

    products:
        sheet_name: Products
        target_table: products

    orders:
        sheet_name: Orders
        target_table: orders

    order_items:
        sheet_name: OrderItems
        target_table: order_items

#--------------#
# Column rules #
#--------------#

columns:
    customers:
        customer_id:
            source_column: id
            data_type: integer
            primary_key: true
            validation:
                min_value: 1

        customer_name:
            source_column: customer_name
            data_type: string
            format: person_name

        email:
            source_column: email
            data_type: string
            format: email

        mobile:
            source_column: mobile
            data_type: string
            format: mobile

        city:
            source_column: city
            data_type: string

        join_date:
            source_column: join_date
            data_type: date
            format: YYYY-MM-DD
            validation:
                min_value: 1900-01-01
                max_value: today

    products:
        product_id:
            source_column: product_id
            data_type: integer
            primary_key: true
            validation:
                min_value: 1001

        product_name:
            source_column: product_name
            data_type: string
            format: product_name

        product_price:
            source_column: product_price
            data_type: float
            format: currency
            validation:
                min_value: 1
                max_value: 1000000

        stock_quantity:
            source_column: stock_quantity
            data_type: integer
            validation:
                min_value: 0
                max_value: 1000000

    orders:
        order_id:
            source_column: order_id
            data_type: integer
            primary_key: true
            validation:
                min_value: 100

        customer_id:
            source_column: customer_id
            data_type: integer
            validation:
                foreign_key: customers.customer_id

        order_date:
            source_column: order_date
            data_type: date
            format: YYYY-MM-DD
            validation:
                min_value: 1900-01-01
                max_value: today

    order_items:
        order_item_id:
            source_column: order_item_id
            data_type: integer
            primary_key: true

        order_id:
            source_column: order_id
            data_type: integer
            validation:
                foreign_key: orders.order_id

        product_id:
            source_column: product_id
            data_type: integer
            validation:
                foreign_key: products.product_id

        quantity:
            source_column: quantity
            data_type: integer
            validation:
                min_value: 1
                max_value: 1000000

        unit_price:
            source_column: unit_price
            data_type: float
            format: currency
            validation:
                min_value: 1
                max_value: 1000000.00

        total_price:
            source_column: total_price
            data_type: float
            format: currency
            validation:
                derived_from:
                    formula: "quantity * unit_price"
                    depends_on:
                        - quantity
                        - unit_price
