# excel_to_sql project configuration
# sql first configuation

#---------------#
# Target config #
#---------------#

active_target: "sqlite"    

targets:
    mssql:
        driver: "ODBC Driver 17 for SQL Server"
        server: "localhost"
        database_name: "order_management"
        authentication:
            type: "windows" # "sql" or "windows"
            username: "my_user"
            password: "my_password"
        schema: "dbo"
        if_exists: "append"
        batch_size: 1000
        fast_executemany: true

    sqlite:
        database_name: "order_management"
        if_exists: "replace"   # or "append"
        batch_size: 1000

    postgres:
        host: "localhost"
        port: 5432
        database: "order_management"
        username: "postgres"
        password: "secret"
        schema: "public"
        if_exists: "append"
        batch_size: 1000        