# excel_to_sql project configuration

#-------#
# Paths #
#-------#
# Path to raw data (relative to project root)
data_dir: ./data/raw
log_dir: /logs

#---------------#
# project config #
#---------------#
project_name: excel_to_sql
config_file: pipeline_config.yaml